- name: Set up MongoDB Repo
  ansible.builtin.copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongodb.repo

- name: Install MongoDB Package
  ansible.builtin.yum:
    name: mongodb-org
    state: installed

- name: Updating Mongodb Listen address
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: Starting MongoDB service
  ansible.builtin.systemd:
    name: mongod
    state: restarted
    enabled: yes

- name: Downloading and Extract schema files
  ansible.builtin.unarchive:
    src: https://github.com/roboshop-devops-project/mongodb/archive/main.zip
    dest: /tmp
    remote_src: yes

#- name: Load Catalogue Schema
#  community.mongodb.mongodb_shell:
#   file: "/tmp/mongodb-main/catalogue.js"
#    idempotent: yes # every time it will not recreate a new schema

#- name: Load Users Schema
#  community.mongodb.mongodb_shell:
#    file: "/tmp/mongodb-main/users.js"
#    idempotent: yes

#Apply loops here

- name: Load Component Schema
  community.mongodb.mongodb_shell:
    file: "/tmp/mongodb-main/{{item}}.js"
    idempotent: yes
  loop:
    - catalogue
    - users


