- name: Frontend Setup
  hosts: FRONTEND
  roles:
    - frontend

- name: MongoDB Setup
  hosts: MONGODB
  roles:
    - mongodb

- name: REDIS Setup
  hosts: REDIS
  roles:
    - redis

- name: Cart Setup
  hosts: CART
  roles:
    - cart

- name: User Setup
  hosts: USER
  roles:
    - user

- name: MySQL Setup
  hosts: MYSQL
  roles:
    - mysql

- name: Shipping Setup
  hosts: SHIPPING
  roles:
    - shipping

- name: Payment Setup
  hosts: PAYMENT
  roles:
    - payment

- name: Rabbitmq Setup
  hosts: RABBITMQ
  roles:
    - rabbitmq
