- name: Add Roboshop Application User
  ansible.builtin.user:
    name: roboshop

- name: Clean old App Content
  ansible.builtin.file:
    path: /home/roboshop/{{COMPONENT}}
    state: absent

- name: Downloading Application content
  ansible.builtin.unarchive:
    src: https://github.com/roboshop-devops-project/{{COMPONENT}}/archive/main.zip
    dest: /tmp
    remote_src: yes

# copy/move files from /tmp (/tmp/catalogue-main/) to  /home/roboshop/catalogue/

- name: Copy Extracted App content
  ansible.builtin.copy:
    src: /tmp/catalogue-main/
    dest: /home/roboshop/{{COMPONENT}}/
    remote_src: yes


